### PR TITLE
Adds global flag to prevent "local variable 'opened_cache' referenced…

### PR DESCRIPTION
**Pull request by tjj5036**
… before assignment" error

Ran into this using Pistachio 2.1.3 in a project:

```  File "/Users/tjones/projects/ads_rest_api/adsvenv/lib/python2.7/site-packages/pistachio/main.py", line 22, in load
    loaded_cache = cache.load(s)
  File "/Users/tjones/projects/ads_rest_api/adsvenv/lib/python2.7/site-packages/pistachio/cache.py", line 14, in load
    if is_valid(settings):
  File "/Users/tjones/projects/ads_rest_api/adsvenv/lib/python2.7/site-packages/pistachio/cache.py", line 47, in is_valid
    loaded = read(cache)
  File "/Users/tjones/projects/ads_rest_api/adsvenv/lib/python2.7/site-packages/pistachio/cache.py", line 38, in read
    if not opened_cache:
UnboundLocalError: local variable 'opened_cache' referenced before assignment```

Tested this locally and works great.

### CODE REVIEW

**Comment by lee12jin** [comment]
LGTM, could you also up the version

**Comment by lee12jin** [comment]
@jsm Could you release a new version

**Comment by tjj5036** [comment]
@lee12jin Bumped from 2.1.3 to 2.1.4!

**Comment by lee12jin** [comment]
Sweet, thanks for catching this @tjj5036

**Pull request merged**
