### PR TITLE
check if cache exists before checking its mtime

### PR DESCRIPTION
**Pull request by heph**
fixes an OSError when the cache doesn't exist

@lee12jin and/or @jsm please review

### CODE REVIEW

**Comment by lee12jin** [comment]
LGTM :+1:

**Comment by jsm** [comment]
I don't see why this is necessary? It already checks for that here: https://github.com/optimizely/pistachio/blob/master/pistachio/cache.py#L14
before is_expired is called

**Comment by heph** [comment]
probably was bailing out when called directly from here: https://github.com/optimizely/pistachio/blob/master/pistachio/settings.py#L118

**Comment by jsm** [comment]
The problem with that is if you're passing in a cachefile and it doesn't it exist, you're saying that is_expired is false.

It would be better to fix the calling logic to check separately that the cache exists (which should be put in a helper function considering the logic is done multiple times in separate places)

or rename the function to exists_and_is_expired or something that accurately shows what the function is doing

**Pull request merged**
