### PR TITLE
Jin/dot pistachio remove

### PR DESCRIPTION
**Pull request by lee12jin**
@heph @Codonaut @kylerandolph Please review. Purpose: Get rid of keys and secrets defined within .pistachio files. This will enable us to secure our keys and secrets and also get rid of the shared developers access (for better auditing).

### CODE REVIEW

**Comment by lee12jin** [comment]
Will not merge this diff in until we have given developers ample time to switch over to Okta and chrome-assumeRoleWithSaml

**Comment by lee12jin** [comment]
Rebased

**Comment by lee12jin** [comment]
@jsm feel free to code review this as well. This is bound to be merged pretty soon.

**Comment by Codonaut** [comment]
lgtm

**Comment by heph** [comment]
:shipit:

**Pull request merged**
